import React from 'react'
import AllCategoriesLandingPage from './AllCategoriesLandingPage'

export const metadata = {
    title: "Raj Parampara | A Beauty Like Magic",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <div>
            <AllCategoriesLandingPage />
        </div>
    )
}
